// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/smf.proto

package smf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AMF 向 SMF 请求建立会话
type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UeId          string                 `protobuf:"bytes,1,opt,name=ue_id,json=ueId,proto3" json:"ue_id,omitempty"`            // 设备ID
	AmfUeId       string                 `protobuf:"bytes,2,opt,name=amf_ue_id,json=amfUeId,proto3" json:"amf_ue_id,omitempty"` // AMF分配的内部ID
	Dnn           string                 `protobuf:"bytes,3,opt,name=dnn,proto3" json:"dnn,omitempty"`                          // 数据网络名称，比如 "internet"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_smf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_smf_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetUeId() string {
	if x != nil {
		return x.UeId
	}
	return ""
}

func (x *CreateSessionRequest) GetAmfUeId() string {
	if x != nil {
		return x.AmfUeId
	}
	return ""
}

func (x *CreateSessionRequest) GetDnn() string {
	if x != nil {
		return x.Dnn
	}
	return ""
}

// SMF 返回会话结果
type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // SMF分配的会话ID
	UeIp          string                 `protobuf:"bytes,3,opt,name=ue_ip,json=ueIp,proto3" json:"ue_ip,omitempty"`                // 分配给UE的IP地址
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_proto_smf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_smf_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetUeIp() string {
	if x != nil {
		return x.UeIp
	}
	return ""
}

func (x *CreateSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 删除会话
type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UeId          string                 `protobuf:"bytes,2,opt,name=ue_id,json=ueId,proto3" json:"ue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_proto_smf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_smf_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *DeleteSessionRequest) GetUeId() string {
	if x != nil {
		return x.UeId
	}
	return ""
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_proto_smf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_smf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_smf_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteSessionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_smf_proto protoreflect.FileDescriptor

const file_proto_smf_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/smf.proto\x12\x03smf\"Y\n" +
	"\x14CreateSessionRequest\x12\x13\n" +
	"\x05ue_id\x18\x01 \x01(\tR\x04ueId\x12\x1a\n" +
	"\tamf_ue_id\x18\x02 \x01(\tR\aamfUeId\x12\x10\n" +
	"\x03dnn\x18\x03 \x01(\tR\x03dnn\"\x7f\n" +
	"\x15CreateSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x13\n" +
	"\x05ue_ip\x18\x03 \x01(\tR\x04ueIp\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"J\n" +
	"\x14DeleteSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x13\n" +
	"\x05ue_id\x18\x02 \x01(\tR\x04ueId\"K\n" +
	"\x15DeleteSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9c\x01\n" +
	"\n" +
	"SMFService\x12F\n" +
	"\rCreateSession\x12\x19.smf.CreateSessionRequest\x1a\x1a.smf.CreateSessionResponse\x12F\n" +
	"\rDeleteSession\x12\x19.smf.DeleteSessionRequest\x1a\x1a.smf.DeleteSessionResponseB\x1eZ\x1cgithub.com/5g-core/proto/smfb\x06proto3"

var (
	file_proto_smf_proto_rawDescOnce sync.Once
	file_proto_smf_proto_rawDescData []byte
)

func file_proto_smf_proto_rawDescGZIP() []byte {
	file_proto_smf_proto_rawDescOnce.Do(func() {
		file_proto_smf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_smf_proto_rawDesc), len(file_proto_smf_proto_rawDesc)))
	})
	return file_proto_smf_proto_rawDescData
}

var file_proto_smf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_smf_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),  // 0: smf.CreateSessionRequest
	(*CreateSessionResponse)(nil), // 1: smf.CreateSessionResponse
	(*DeleteSessionRequest)(nil),  // 2: smf.DeleteSessionRequest
	(*DeleteSessionResponse)(nil), // 3: smf.DeleteSessionResponse
}
var file_proto_smf_proto_depIdxs = []int32{
	0, // 0: smf.SMFService.CreateSession:input_type -> smf.CreateSessionRequest
	2, // 1: smf.SMFService.DeleteSession:input_type -> smf.DeleteSessionRequest
	1, // 2: smf.SMFService.CreateSession:output_type -> smf.CreateSessionResponse
	3, // 3: smf.SMFService.DeleteSession:output_type -> smf.DeleteSessionResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_smf_proto_init() }
func file_proto_smf_proto_init() {
	if File_proto_smf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_smf_proto_rawDesc), len(file_proto_smf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_smf_proto_goTypes,
		DependencyIndexes: file_proto_smf_proto_depIdxs,
		MessageInfos:      file_proto_smf_proto_msgTypes,
	}.Build()
	File_proto_smf_proto = out.File
	file_proto_smf_proto_goTypes = nil
	file_proto_smf_proto_depIdxs = nil
}
